### ISSUE TITLE
pyuic6: Calls the wrong command

### ISSUE THREAD

**Issue by PHermans1** [Abdelatief/Pyuic5-Tool#1]
I know this tool was created for pyuic5, but i want to do the same thing for pyuic6. I think all it takes is changing a single line of code, but wonder how to get this done.  Happy to help, I just know very little about creating packages etc.

**Comment by Abdelatief** [comment]
I don't know about pyuic6 tho but if you just want to use that command instead of pyuic5 you could copy the code from [converter.py file](https://github.com/Abdelatief/Pyuic5-Tool/blob/master/src/converter.py)  and paste in wherever you like in your code and just edit  [line 78](https://github.com/Abdelatief/Pyuic5-Tool/blob/8cf54d52257c6be76e9491b8261da71dbf7638c5/src/converter.py#L78) 
`system(f'pyuic5 {absolute_uifile_path} -o {absolute_pyfile_path}')`  to 
`system(f'pyuic6 {absolute_uifile_path} -o {absolute_pyfile_path}')`
or if you installed the package using pip you'd find the converter.py file in the site-packages folder in your environment
